### ISSUE TITLE
Feature request: don't make me think :)

### ISSUE THREAD

**Issue by bobthecow** [SublimeText/RevertFontSize#2]
1. Great work so far!
2. Moving things into default preferences was a good call.
3. It could be even better :)

On initial install, it would be great if it would simply copy my current font size to the `revert_font_size` key in my preferences. I don't know enough about Sublime packages to know if this is possible, but it looks like Package Control modifies my default prefs file, so it should be.

**Comment by FichteFoll** [comment]
Would be easy to test whether the key exists and if not, read a default value from the `"font_size"` setting.

On the other hand, when uninstalling this the setting automatically added by the plugin will not be removed automacally. Usually you won't install this without changing that setting but it could be considered. Should be mentioned in the readme (and possibly on installation through Package Control).

Edit: As long as ST is running when the package is uninstalled (e.g. with Package Control's "Remove Package") you should be able to hook into "plugin_unloaded" and remove the setting.

**Comment by hced** [comment]
I agree. Parsing for existing "font_size" property in Packages/User/Preferences.sublime-settings and if it exists, use that. If it doesn't exist, one might assume that the user doesn't care about default font size in the first place.

**Comment by jsadeli** [comment]
I tried looking at a way to do this ~2 weekish ago, but couldn't find a good event to attach to (the event where sublime has finished loading all its preferences, specifically the `User\Preferences.sublime-settings`).

Granted that there are many events that fits the job: such as the `on_load(view)` event, but that event seems excessive (will get called repeatedly on every file load, thus seems unnecessarily wasteful).

**Comment by FichteFoll** [comment]
@jsadeli http://www.sublimetext.com/forum/viewtopic.php?f=2&t=10895 for ST3. ST2 loads settings before initializing plugins so that should be possible in the "top most level".

**Comment by bobthecow** [comment]
@hced: If they don't care about the default font size in the first place, why did they install RevertFontSize? ;)

**Comment by hced** [comment]
@bobthecow: you're right. And so I believe they're not a user base to cater for, meaning, those users (probably non-existent) would have to stick with whatever is the default font_size (I believe 10) in Packages/Default/Preferences.sublime-settings, if they happen to use the plugin.

I might actually confuse things with above... But all I'm saying is, I suggest just getting the builtin font_size property in user or default preferences and dump the revert_font_size one, especially having it used as a setter for default font_size (!), which doesn't make sense to me. Rationale being that if you set a custom font_size, or, are satisfied with the default font_size of 10, that's what you're happy with and consider to be the default size to revert to. Right?
