### ISSUE TITLE
Enable for ST3

### ISSUE THREAD

**Issue by raineorshine** [SublimeText/RevertFontSize#3]
Would you enable this as a ST3 plugin in [Package Control](https://sublime.wbond.net/packages/RevertFontSize)? I installed it locally and it works fine in ST3, but it isn't listed in the available Package Control packages I think because it is marked as ST2-only. Thanks!

**Comment by jsadeli** [comment]
Alright, I'll give it a look.

**Comment by chibicode** [comment]
:+1:

**Comment by jsadeli** [comment]
https://github.com/wbond/package_control_channel/pull/3097
