### ISSUE TITLE
Font size is not reverted in ST3

### ISSUE THREAD

**Issue by KatieK2** [SublimeText/RevertFontSize#5]
I just installed via package control into Sublime Text 3 on Windows 7, but I can't seem to get this working.  From a +2 font size, if I do Ctrl 0, the font size doesn't change, when I would expect it to change to the same font size that Prefernces > Font > Reset uses. 

I've even tried specifying the Revert Value via Ctrl Shift 0, but that doesn't help. The ST console doesn't provide any errors and I've restarted ST. I'm using the Oblivion Soda Dark color scheme, but changing to Monokai didn't help.

**Comment by jsadeli** [comment]
If you check Sublime Text's user preferences, do you see an entry for "revert_font_size"?

**Comment by KatieK2** [comment]
Yes:

```
    "revert_font_size": 13,
```

**Comment by jsadeli** [comment]
Another one that I can think of is that there's a key binding conflict with another package or user. The one option is to disable installed packages until it starts working - a bit time consuming.

**Comment by FichteFoll** [comment]
No, there is a better option for working with overridden key bindings: Overriding them again in you user bindings.

You can easily confirm whether a key binding does what it should by entering `sublime.log_commands(True)` in the console and then monitoring it.

**Comment by KatieK2** [comment]
By turning on console logging, I was able to determine that `command: revert_font_size` does fire (and the text size changes) when I use the 0 from the standard number keys above the alphas, but **not** when I used the 0 on the numerical keypad, even with numlock enabled. 

Please let me know if you would like me to write a separate bug / feature from this issue. Thanks!

**Comment by FichteFoll** [comment]
This is working as intended because the numpad 0 key goes by the name `keypad0`. So, were you always trying with the numpad 0 and was this the reason why it didn't work?

In order to make it also work with the numpad, you have to define the following keybinding:

``` js
    { "keys": ["ctrl+keypad0"], "command": "revert_font_size" },
```

Edit: By the way, I was able to find this using `sublime.log_input(True)`.

**Comment by KatieK2** [comment]
Yes, I had been using keypad0; I usually increase or decrease the text size with the keypad's plus and minus since it's easier to find by feel. I didn't expect any difference between standard? and keypad 0, since +/- work the same way. Thanks for the reference to `"ctrl+keypad0"`!
